version: "3.8"

services:
  postgresql:
    container_name: postgresql
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
      - POSTGRES_DB=mydatabase
    volumes:
      - admin-manage-system-postgresql-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      - postgresql
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    
    volumes:
      - admin-manage-system-pgadmin-data:/var/lib/pgadmin

volumes:
  admin-manage-system-postgresql-data:
  admin-manage-system-pgadmin-data: